name: your_project_name
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'  # Adjust the SDK version as needed

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
